from __future__ import annotations

import os
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
os.environ.setdefault("MPLCONFIGDIR", str(ROOT / ".mplconfig"))

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401


B_DIR = Path("/home/lux_liang/work/projects/github/数模校赛B题")
OUT = ROOT / "figures" / "paper"
GEN_OUT = ROOT / "figures" / "generated"

TIME_COL = "时间(s)"
X_COL = "X坐标(m)"
Y_COL = "Y坐标(m)"

BLUE = "#356EA9"
TEAL = "#2A9D8F"
ORANGE = "#D97732"
GRAY = "#6B7280"
DARK = "#253238"
GOLD = "#D8A31A"
RED = "#B94A48"


def setup() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    GEN_OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "v4").mkdir(parents=True, exist_ok=True)
    font_path = "/home/lux_liang/.local/texlive/2026/texmf-dist/fonts/opentype/public/fandol/FandolHei-Regular.otf"
    if Path(font_path).exists():
        mpl.font_manager.fontManager.addfont(font_path)
        zh_font = "FandolHei"
    else:
        zh_font = "DejaVu Sans"
    mpl.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": [zh_font],
            "axes.unicode_minus": False,
            "font.size": 10.5,
            "axes.labelsize": 10.5,
            "axes.titlesize": 11.5,
            "legend.fontsize": 9.2,
            "xtick.labelsize": 9.2,
            "ytick.labelsize": 9.2,
            "axes.linewidth": 0.75,
            "lines.linewidth": 1.35,
            "figure.dpi": 160,
            "savefig.dpi": 320,
            "savefig.bbox": "tight",
            "pdf.use14corefonts": False,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def save(path: Path) -> None:
    plt.tight_layout(pad=0.7)
    plt.savefig(path)
    plt.close()


def save_both(fig: plt.Figure, stem: str, dpi: int = 360) -> None:
    for suffix in [".pdf", ".png"]:
        path = OUT / "v4" / f"{stem}{suffix}"
        kwargs = {"bbox_inches": "tight", "pad_inches": 0.04}
        if suffix == ".png":
            kwargs["dpi"] = dpi
        fig.savefig(path, **kwargs)
    plt.close(fig)


def copy_v4_figures() -> None:
    """Copy v4 modeling figures generated by the coding repository into the paper tree."""

    names = [
        "attachment1_time_alignment.pdf",
        "attachment2_method_rmse_compare.pdf",
        "attachment2_trajectory_kalman_rts.pdf",
        "attachment2_residual_distribution_compare.pdf",
        "attachment3_residual_time_trend_clean.pdf",
        "attachment3_residual_vector_field_clean.pdf",
        "attachment3_bias_model_cv_compare_clean.pdf",
        "attachment3_residual_state_relation_clean.pdf",
        "attachment2_kalman_denoising.pdf",
        "attachment2_residual_before_after_kalman.pdf",
        "attachment3_residual_time_trend.pdf",
        "attachment3_residual_vector_field.pdf",
        "attachment3_bias_model_comparison.pdf",
        "attachment3_residual_vs_state.pdf",
        "shooting_hit_probability_distribution.pdf",
        "photo_multi_target_coverage.pdf",
        "joint_task_gantt.pdf",
        "joint_task_spatial_distribution.pdf",
        "joint_risk_tradeoff_curve.pdf",
    ]
    for name in names:
        src = B_DIR / "outputs" / "figures" / name
        if src.exists():
            shutil.copyfile(src, OUT / "v4" / name)


def plot_fov_risk_sensitivity() -> None:
    """Draw separated sensitivity panels for camera FOV and risk preference."""

    fov = pd.read_csv(B_DIR / "outputs" / "tables" / "photo_fov_sensitivity.csv")
    risk = pd.read_csv(B_DIR / "outputs" / "tables" / "joint_risk_tradeoff_curve.csv")
    labels = ["A0", "A1", "A2", "B", "B2"]
    fig, axes = plt.subplots(2, 2, figsize=(9.8, 6.4))

    ax = axes[0, 0]
    ax.plot(fov["fov_degree"], fov["covered_targets"], marker="o", color=BLUE, label="覆盖目标数")
    ax.plot(fov["fov_degree"], fov["total_target_observations"], marker="s", color=TEAL, label="总观测次数")
    ax.plot(fov["fov_degree"], fov["multi_target_events"], marker="^", color=ORANGE, label="多目标同拍事件")
    ax.set_xlabel("视场角 FOV / 度")
    ax.set_ylabel("数量 / 个")
    ax.set_title("(a) 感知视场角")
    ax.set_xticks(fov["fov_degree"])
    ax.legend(frameon=False, loc="upper left")

    ax = axes[0, 1]
    x = risk["min_margin_filter"].replace(-1.0, 0.0)
    ax.plot(x, risk["combined_target_utility"], marker="o", color=BLUE)
    ax.set_xlabel("最小裕度阈值")
    ax.set_ylabel("综合效用")
    ax.set_title("(b) 裕度阈值与综合效用")

    ax = axes[1, 0]
    ax.bar(np.arange(len(risk)), risk["risk_count"], width=0.55, color=RED, alpha=0.84)
    ax.set_xticks(np.arange(len(risk)), labels)
    ax.set_xlabel("方案族")
    ax.set_ylabel("高风险事件数")
    ax.set_title("(c) 方案族高风险事件数")

    ax = axes[1, 1]
    ax.plot(np.arange(len(risk)), risk["scenario_pass_rate"], marker="o", color=TEAL)
    ax.set_xticks(np.arange(len(risk)), labels)
    ax.set_xlabel("方案族")
    ax.set_ylabel("场景通过率")
    ax.set_ylim(0.84, 1.0)
    ax.set_title("(d) 方案族场景通过率")

    for ax in axes.flat:
        style_axis(ax)
    fig.suptitle("视场角、裕度阈值与鲁棒性灵敏度", y=0.995, fontsize=12.0)
    fig.subplots_adjust(left=0.08, right=0.98, top=0.90, bottom=0.09, wspace=0.28, hspace=0.44)
    save_both(fig, "fov_risk_sensitivity")


def plot_attachment1_split_v4() -> None:
    raw1, raw2 = read_raw(1)
    fused = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment1_10hz.csv")
    delta = pd.read_csv(B_DIR / "outputs" / "tables" / "delta_objective_attachment1.csv")

    fig, axes = plt.subplots(1, 2, figsize=(9.4, 4.0))
    axes[0].plot(raw1[X_COL], raw1[Y_COL], color=BLUE, label="定位方式1", alpha=0.95)
    axes[0].plot(raw2[X_COL], raw2[Y_COL], color=ORANGE, label="定位方式2", alpha=0.75)
    axes[0].set_title("(a) 时间对齐前")
    axes[1].plot(fused["x1_aligned"], fused["y1_aligned"], color=BLUE, label="定位方式1")
    axes[1].plot(fused["x2_aligned_corrected"], fused["y2_aligned_corrected"], color=ORANGE, linestyle=(0, (4, 2)), label="对齐后的定位方式2")
    axes[1].set_title("(b) 时间对齐后")
    for ax in axes:
        ax.set_xlabel("X 坐标 / m")
        ax.set_ylabel("Y 坐标 / m")
        style_axis(ax, equal=True)
        ax.legend(frameon=False)
    for path in [OUT / "v4" / "attachment1_trajectory_alignment_split.pdf", OUT / "v4" / "attachment1_trajectory_alignment_split.png"]:
        kwargs = {"bbox_inches": "tight", "pad_inches": 0.04}
        if path.suffix == ".png":
            kwargs["dpi"] = 360
        fig.savefig(path, **kwargs)
    plt.close(fig)

    fig, axes = plt.subplots(1, 2, figsize=(9.4, 3.9))
    best = delta.loc[delta["RMSE"].idxmin()]
    axes[0].plot(delta["Delta"], delta["RMSE"], color=BLUE)
    axes[0].scatter([best["Delta"]], [best["RMSE"]], s=42, color=RED, zorder=5, label="最优 Delta")
    axes[0].set_xlabel("时间偏差 Delta / s")
    axes[0].set_ylabel("RMSE / m")
    axes[0].set_title("(a) 时间偏差搜索曲线")
    axes[0].legend(frameon=False)
    axes[1].plot(fused[TIME_COL], fused[X_COL], color=BLUE, label="X 坐标")
    axes[1].plot(fused[TIME_COL], fused[Y_COL], color=ORANGE, label="Y 坐标")
    axes[1].set_xlabel("时间 / s")
    axes[1].set_ylabel("融合坐标 / m")
    axes[1].set_title("(b) 10 Hz 融合轨迹坐标")
    axes[1].legend(frameon=False)
    for ax in axes:
        style_axis(ax)
    for path in [OUT / "v4" / "attachment1_rmse_10hz_split.pdf", OUT / "v4" / "attachment1_rmse_10hz_split.png"]:
        kwargs = {"bbox_inches": "tight", "pad_inches": 0.04}
        if path.suffix == ".png":
            kwargs["dpi"] = 360
        fig.savefig(path, **kwargs)
    plt.close(fig)


def plot_risk_tradeoff_clean() -> None:
    risk = pd.read_csv(B_DIR / "outputs" / "tables" / "joint_risk_tradeoff_curve.csv")
    labels = ["A0", "A1", "A2", "B", "B2"]
    colors = [BLUE, BLUE, TEAL, ORANGE, ORANGE]
    sizes = 42 + 12 * risk["photo_targets_covered"].to_numpy(float)
    fig, ax = plt.subplots(figsize=(7.4, 4.9))
    ax.scatter(risk["risk_count"], risk["combined_target_utility"], s=sizes, c=colors, edgecolor=DARK, linewidth=0.5, zorder=3)
    offsets = {
        "A0": (8, 7),
        "A1": (8, -13),
        "A2": (8, 8),
        "B": (-28, 8),
        "B2": (-30, -13),
    }
    for label, (_, row) in zip(labels, risk.iterrows()):
        ax.annotate(label, (row["risk_count"], row["combined_target_utility"]), xytext=offsets[label], textcoords="offset points", fontsize=9.0,
                    bbox=dict(boxstyle="round,pad=0.18", fc="white", ec="#C9CED6", lw=0.6, alpha=0.92))
    ax.annotate("风险下降方向", xy=(0.2, risk["combined_target_utility"].iloc[-2]), xytext=(3.55, 11.72),
                arrowprops=dict(arrowstyle="->", color=GRAY, lw=1.0), color=GRAY, fontsize=9.2)
    ax.set_xlabel("高风险事件数")
    ax.set_ylabel("综合效用")
    ax.set_title("收益--风险 Pareto 方案族散点图")
    ax.set_xlim(-0.7, risk["risk_count"].max() + 0.7)
    ax.set_ylim(risk["combined_target_utility"].min() - 0.6, risk["combined_target_utility"].max() + 0.6)
    handles = [
        mpl.lines.Line2D([0], [0], marker="o", color="w", label="收益优先", markerfacecolor=BLUE, markeredgecolor=DARK, markersize=7),
        mpl.lines.Line2D([0], [0], marker="o", color="w", label="均衡", markerfacecolor=TEAL, markeredgecolor=DARK, markersize=7),
        mpl.lines.Line2D([0], [0], marker="o", color="w", label="裕度优先", markerfacecolor=ORANGE, markeredgecolor=DARK, markersize=7),
    ]
    ax.legend(handles=handles, frameon=False, loc="upper center", bbox_to_anchor=(0.5, -0.12), ncol=3)
    style_axis(ax)
    fig.subplots_adjust(left=0.10, right=0.98, bottom=0.22, top=0.90)
    save_both(fig, "joint_risk_tradeoff_curve_clean")


def plot_attachment2_clean_v4() -> None:
    fused = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment2_10hz.csv")
    res = pd.read_csv(B_DIR / "outputs" / "tables" / "attachment2_residuals.csv")

    fig, ax = plt.subplots(figsize=(6.8, 5.1))
    ax.plot(fused["x1_aligned"], fused["y1_aligned"], color=BLUE, label="定位方式1", alpha=0.95)
    ax.plot(fused["x2_aligned_corrected"], fused["y2_aligned_corrected"], color=ORANGE, linestyle=(0, (4, 2)), label="方式2鲁棒校正")
    ax.plot(fused[X_COL], fused[Y_COL], color=DARK, linewidth=1.15, label="10 Hz 融合轨迹")
    ax.scatter(fused[X_COL].iloc[0], fused[Y_COL].iloc[0], s=42, color=TEAL, zorder=5, label="起点")
    ax.scatter(fused[X_COL].iloc[-1], fused[Y_COL].iloc[-1], s=42, color=RED, zorder=5, label="终点")
    ax.set_xlabel("X 坐标 / m")
    ax.set_ylabel("Y 坐标 / m")
    ax.set_title("附件2时空配准与融合轨迹")
    style_axis(ax, equal=True)
    ax.legend(frameon=False, loc="upper left", bbox_to_anchor=(1.02, 1.0), borderaxespad=0.0)
    fig.subplots_adjust(right=0.78)
    save_both(fig, "attachment2_trajectory_kalman_rts")

    fig, axes = plt.subplots(1, 2, figsize=(9.2, 4.0))
    before = np.sqrt(res["residual_x_before"] ** 2 + res["residual_y_before"] ** 2)
    after = np.sqrt(res["residual_x_after"] ** 2 + res["residual_y_after"] ** 2)
    axes[0].boxplot([before, after], tick_labels=["校正前", "校正后"], patch_artist=True, boxprops={"facecolor": "#DCE9F6", "color": BLUE}, medianprops={"color": RED})
    axes[0].set_ylabel("残差范数 / m")
    axes[0].set_title("(a) 残差范数对比")
    sample = res.sample(min(1600, len(res)), random_state=7)
    axes[1].scatter(sample["residual_x_after"], sample["residual_y_after"], s=7, color=BLUE, alpha=0.35, edgecolors="none")
    axes[1].axhline(0, color=GRAY, linewidth=0.9)
    axes[1].axvline(0, color=GRAY, linewidth=0.9)
    axes[1].set_xlabel("X 残差 / m")
    axes[1].set_ylabel("Y 残差 / m")
    axes[1].set_title("(b) 校正后残差散点")
    for ax in axes:
        style_axis(ax)
    save_both(fig, "attachment2_residual_distribution_compare")


def add_speed_columns(traj: pd.DataFrame) -> pd.DataFrame:
    work = traj.copy()
    if "speed" in work.columns:
        work["plot_speed"] = work["speed"]
        return work
    t = work[TIME_COL].to_numpy(float)
    x = work[X_COL].to_numpy(float)
    y = work[Y_COL].to_numpy(float)
    vx = np.gradient(x, t)
    vy = np.gradient(y, t)
    work["plot_speed"] = np.sqrt(vx * vx + vy * vy)
    return work


def plot_time_space_speed_3d() -> None:
    """Draw time-parameterized 3D trajectory scatter for problems 1 and 2."""

    datasets = [
        ("附件 1：无噪声对齐轨迹", "fused_attachment1_10hz.csv"),
        ("附件 2：含噪融合轨迹", "fused_attachment2_10hz.csv"),
    ]
    fig = plt.figure(figsize=(12.0, 5.0), constrained_layout=False)
    gs = fig.add_gridspec(1, 3, width_ratios=[1.0, 1.0, 0.045], wspace=0.22)
    norm_values = []
    frames = []
    for _, name in datasets:
        df = add_speed_columns(pd.read_csv(B_DIR / "outputs" / "trajectories" / name))
        frames.append(df)
        norm_values.append(df["plot_speed"].quantile(0.98))
    vmax = float(max(norm_values))
    vmin = 0.0
    axes = []

    for idx, ((title, _), df) in enumerate(zip(datasets, frames), start=1):
        step = max(1, len(df) // 650)
        sample = df.iloc[::step, :].copy()
        ax = fig.add_subplot(gs[0, idx - 1], projection="3d")
        axes.append(ax)
        sc = ax.scatter(
            sample[X_COL],
            sample[Y_COL],
            sample[TIME_COL],
            c=sample["plot_speed"],
            cmap="viridis",
            vmin=vmin,
            vmax=vmax,
            s=10 if idx == 2 else 9,
            alpha=0.88,
            linewidths=0,
            depthshade=False,
        )
        ax.plot(df[X_COL], df[Y_COL], df[TIME_COL], color="#B8C0C8", linewidth=0.85, alpha=0.80, zorder=1)
        ax.scatter(
            df[X_COL].iloc[0],
            df[Y_COL].iloc[0],
            df[TIME_COL].iloc[0],
            s=58,
            color=TEAL,
            edgecolor="white",
            linewidth=0.9,
            label="起点",
            depthshade=False,
            zorder=5,
        )
        ax.scatter(
            df[X_COL].iloc[-1],
            df[Y_COL].iloc[-1],
            df[TIME_COL].iloc[-1],
            s=58,
            color=RED,
            edgecolor="white",
            linewidth=0.9,
            label="终点",
            depthshade=False,
            zorder=5,
        )
        ax.set_title(title, fontsize=11.3, pad=8)
        ax.set_xlabel("X 坐标 / m", labelpad=8, fontsize=10.8)
        ax.set_ylabel("Y 坐标 / m", labelpad=8, fontsize=10.8)
        ax.set_zlabel("时间 / s", labelpad=10, fontsize=10.8)
        ax.view_init(elev=24, azim=-60)
        ax.tick_params(axis="both", which="major", labelsize=8.8, pad=1)
        ax.zaxis.set_tick_params(labelsize=8.8, pad=3)
        ax.legend(frameon=True, loc="upper left", bbox_to_anchor=(0.02, 0.98), fontsize=8.6, framealpha=0.92, edgecolor="#D7DCE2")
        for axis in (ax.xaxis, ax.yaxis, ax.zaxis):
            axis.pane.set_facecolor((0.98, 0.985, 0.99, 0.55))
            axis.pane.set_edgecolor((0.84, 0.87, 0.91, 0.65))
            axis._axinfo["grid"]["color"] = (0.72, 0.77, 0.82, 0.22)
            axis._axinfo["grid"]["linewidth"] = 0.55
        ax.set_box_aspect((1.0, 1.0, 1.22))

    cax = fig.add_subplot(gs[0, 2])
    norm = mpl.colors.Normalize(vmin=vmin, vmax=vmax)
    sm = mpl.cm.ScalarMappable(norm=norm, cmap="viridis")
    sm.set_array([])
    cbar = fig.colorbar(sm, cax=cax)
    cbar.set_label(r"速度 / (m·s$^{-1}$)", fontsize=10.5, labelpad=8)
    cbar.ax.tick_params(labelsize=8.8)
    cbar.outline.set_linewidth(0.7)

    fig.suptitle("时间参数化三维轨迹与速度散点", y=0.97, fontsize=12.0)
    fig.subplots_adjust(left=0.04, right=0.94, bottom=0.06, top=0.88, wspace=0.22)
    for suffix in [".pdf", ".png"]:
        path = OUT / "v4" / f"time_space_speed_3d{suffix}"
        kwargs = {"bbox_inches": "tight", "pad_inches": 0.05}
        if suffix == ".png":
            kwargs["dpi"] = 300
        fig.savefig(path, **kwargs)
    plt.close(fig)


def plot_attachment12_comparison() -> None:
    """Compare attachment 1 and 2 on alignment, residual and trajectory evidence."""

    a1 = pd.read_csv(B_DIR / "outputs" / "tables" / "attachment1_alignment_summary.csv")
    a2 = pd.read_csv(B_DIR / "outputs" / "tables" / "kalman_bias_attachment2_summary.csv")
    a2_base = a2[a2["method"].eq("RobustMedian")].iloc[0]
    rows = pd.DataFrame(
        [
            {
                "dataset": "附件1 无噪声",
                "Delta": float(a1["Delta"].iloc[0]),
                "rmse_before": float(a1["rmse_before"].iloc[0]),
                "rmse_after": float(a1["rmse_after"].iloc[0]),
                "bias_norm": 0.0,
                "residual_sigma": float(a1["rmse_after"].iloc[0]),
                "n_10hz_points": int(a1["n_10hz_points"].iloc[0]),
            },
            {
                "dataset": "附件2 含噪+固定偏差",
                "Delta": float(a2_base["Delta"]),
                "rmse_before": float(a2_base["rmse_before"]),
                "rmse_after": float(a2_base["rmse_after"]),
                "bias_norm": float(np.hypot(a2_base["bx"], a2_base["by"])),
                "residual_sigma": float(np.sqrt(a2_base["residual_var_x"] + a2_base["residual_var_y"])),
                "n_10hz_points": len(pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment2_10hz.csv")),
            },
        ]
    )
    rows.to_csv(OUT / "v4" / "attachment12_alignment_compare.csv", index=False)

    traj1 = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment1_10hz.csv")
    traj2 = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment2_10hz.csv")
    fig, axes = plt.subplots(1, 3, figsize=(11.0, 3.8))

    x = np.arange(len(rows))
    width = 0.34
    axes[0].bar(x - width / 2, rows["rmse_before"], width=width, color="#9AA3AD", label="对齐前 RMSE")
    axes[0].bar(x + width / 2, rows["rmse_after"], width=width, color=BLUE, label="校正后 RMSE")
    axes[0].set_xticks(x, rows["dataset"], rotation=12, ha="right")
    axes[0].set_ylabel("RMSE / m")
    axes[0].set_title("(a) 残差尺度")
    axes[0].legend(frameon=False)

    axes[1].bar(x, rows["bias_norm"], color=[TEAL, ORANGE], alpha=0.86)
    axes[1].set_xticks(x, rows["dataset"], rotation=12, ha="right")
    axes[1].set_ylabel("固定偏差模长 / m")
    axes[1].set_title("(b) 固定偏差幅值")

    def norm_time(s: pd.Series) -> pd.Series:
        return (s - s.min()) / (s.max() - s.min())

    step1 = max(1, len(traj1) // 900)
    step2 = max(1, len(traj2) // 900)
    axes[2].scatter(traj1[X_COL].iloc[::step1], traj1[Y_COL].iloc[::step1], c=norm_time(traj1[TIME_COL].iloc[::step1]), cmap="Blues", s=7, alpha=0.72, label="附件1")
    axes[2].scatter(traj2[X_COL].iloc[::step2], traj2[Y_COL].iloc[::step2], c=norm_time(traj2[TIME_COL].iloc[::step2]), cmap="Oranges", s=7, alpha=0.72, label="附件2")
    axes[2].set_xlabel("X 坐标 / m")
    axes[2].set_ylabel("Y 坐标 / m")
    axes[2].set_title("(c) 10 Hz 融合轨迹")
    axes[2].legend(frameon=False, loc="center left", bbox_to_anchor=(1.02, 0.5), borderaxespad=0.0)
    for ax in axes:
        style_axis(ax)
    fig.subplots_adjust(right=0.80)
    save_both(fig, "attachment12_alignment_compare")


def plot_kinematic_smoothing_compare() -> None:
    """Compare finite-difference kinematics before and after state smoothing."""

    df = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment2_10hz.csv")
    t = df[TIME_COL].to_numpy(float)

    def kin(x: pd.Series, y: pd.Series) -> tuple[np.ndarray, np.ndarray]:
        x_arr = x.to_numpy(float)
        y_arr = y.to_numpy(float)
        vx = np.gradient(x_arr, t)
        vy = np.gradient(y_arr, t)
        speed = np.sqrt(vx * vx + vy * vy)
        ax_arr = np.gradient(vx, t)
        ay_arr = np.gradient(vy, t)
        acc = np.sqrt(ax_arr * ax_arr + ay_arr * ay_arr)
        return speed, acc

    speed_ref, acc_ref = kin(df["x1_aligned"], df["y1_aligned"])
    speed_rts, acc_rts = kin(df[X_COL], df[Y_COL])
    metrics = pd.DataFrame(
        [
            {
                "method": "reference_finite_difference",
                "speed_p95": np.percentile(speed_ref, 95),
                "speed_tv": np.sum(np.abs(np.diff(speed_ref))),
                "acceleration_p95": np.percentile(acc_ref, 95),
                "acceleration_tv": np.sum(np.abs(np.diff(acc_ref))),
            },
            {
                "method": "kalman_rts_state",
                "speed_p95": np.percentile(speed_rts, 95),
                "speed_tv": np.sum(np.abs(np.diff(speed_rts))),
                "acceleration_p95": np.percentile(acc_rts, 95),
                "acceleration_tv": np.sum(np.abs(np.diff(acc_rts))),
            },
        ]
    )
    metrics.to_csv(OUT / "v4" / "attachment2_kinematic_smoothing_metrics.csv", index=False)

    sample = slice(None, None, max(1, len(df) // 2200))
    fig, axes = plt.subplots(2, 1, figsize=(8.4, 5.2), sharex=True)
    axes[0].plot(t[sample], speed_ref[sample], color="#9AA3AD", linewidth=0.9, alpha=0.82, label="参考源有限差分")
    axes[0].plot(t[sample], speed_rts[sample], color=BLUE, linewidth=1.35, label="RTS 平滑状态")
    axes[0].set_ylabel("速度 / (m/s)")
    axes[0].set_title("(a) 速度序列")
    axes[0].legend(frameon=False, ncol=2)
    axes[1].plot(t[sample], acc_ref[sample], color="#9AA3AD", linewidth=0.9, alpha=0.82, label="参考源有限差分")
    axes[1].plot(t[sample], acc_rts[sample], color=ORANGE, linewidth=1.35, label="RTS 平滑状态")
    axes[1].set_xlabel("时间 / s")
    axes[1].set_ylabel("加速度 / (m/s²)", labelpad=10)
    axes[1].set_title("(b) 加速度序列")
    axes[1].legend(frameon=False, ncol=2)
    for ax in axes:
        style_axis(ax)
    fig.suptitle("附件2有限差分与 RTS 状态运动学量对比", y=0.99, fontsize=12.0)
    fig.subplots_adjust(left=0.13, right=0.98, top=0.91, bottom=0.10, hspace=0.30)
    save_both(fig, "attachment2_kinematic_smoothing_compare")


def plot_attachment3_clean_v4() -> None:
    feat = pd.read_csv(B_DIR / "outputs" / "tables" / "attachment3_residual_feature_frame.csv")
    comp = pd.read_csv(B_DIR / "outputs" / "tables" / "attachment3_bias_structure_comparison.csv")

    fig, ax = plt.subplots(figsize=(8.4, 4.2))
    t = feat[TIME_COL]
    rx = feat["residual_x"]
    ry = feat["residual_y"]
    win = max(5, int(len(feat) * 0.035))
    ax.plot(t, rx, color=BLUE, alpha=0.38, linewidth=0.8, label="X 残差")
    ax.plot(t, ry, color=ORANGE, alpha=0.38, linewidth=0.8, label="Y 残差")
    ax.plot(t, rx.rolling(win, center=True, min_periods=1).mean(), color=BLUE, linewidth=1.8, label="X 滑动均值")
    ax.plot(t, ry.rolling(win, center=True, min_periods=1).mean(), color=ORANGE, linewidth=1.8, label="Y 滑动均值")
    ax.axhline(0, color=GRAY, linewidth=0.8)
    ax.set_xlabel("时间 / s")
    ax.set_ylabel("残差 / m")
    ax.set_title("附件3残差时间趋势")
    style_axis(ax)
    ax.legend(frameon=False, ncol=2)
    save_both(fig, "attachment3_residual_time_trend_clean")

    fig, ax = plt.subplots(figsize=(7.0, 4.2))
    x = np.arange(len(comp))
    width = 0.34
    ax.bar(x - width / 2, comp["train_rmse"], width=width, color=BLUE, alpha=0.86, label="训练 RMSE")
    ax.bar(x + width / 2, comp["cv_rmse"], width=width, color=ORANGE, alpha=0.86, label="时间块 CV-RMSE")
    ax.set_xticks(x, comp["model_name"])
    ax.set_xlabel("偏差结构模型")
    ax.set_ylabel("RMSE / m")
    ax.set_title("附件3偏差模型泛化对比")
    style_axis(ax)
    ax.legend(frameon=False, loc="upper center", bbox_to_anchor=(0.5, -0.14), ncol=2)
    fig.subplots_adjust(bottom=0.18)
    save_both(fig, "attachment3_bias_model_cv_compare_clean")


def plot_task_spatial_and_gantt_v4() -> None:
    traj = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment3_10hz.csv")
    targets = read_targets()
    selected = pd.read_csv(B_DIR / "outputs" / "tables" / "joint_selected_events.csv")

    fig, ax = plt.subplots(figsize=(7.6, 5.9))
    ax.plot(traj[X_COL], traj[Y_COL], color="#C8CDD3", linewidth=0.75, alpha=0.70, label="10 Hz 融合轨迹", zorder=1)
    shoot = targets[targets["task"] == "shooting"]
    photo = targets[targets["task"] == "photo"]
    ax.scatter(shoot[X_COL], shoot[Y_COL], s=28, color="#7EA6CB", alpha=0.24, label="全部射击目标", zorder=2)
    ax.scatter(photo[X_COL], photo[Y_COL], s=30, color="#E7A066", alpha=0.24, label="全部拍照目标", zorder=2)
    exec_pos = traj.set_index(TIME_COL).reindex(selected["execute_time"].to_numpy(float), method="nearest").reset_index()
    is_photo = selected["event_type"].eq("photo").to_numpy()
    ax.scatter(exec_pos[X_COL][~is_photo], exec_pos[Y_COL][~is_photo], s=42, marker="o", color=BLUE, edgecolor="white", linewidth=0.65, label="最终射击执行点", zorder=5)
    ax.scatter(exec_pos[X_COL][is_photo], exec_pos[Y_COL][is_photo], s=86, marker="^", color=ORANGE, edgecolor=DARK, linewidth=0.65, label="最终拍照执行点", zorder=6)

    covered_photo = sorted({p for txt in selected.loc[selected["event_type"].eq("photo"), "covered_targets"].astype(str) for p in txt.split(",")})
    covered = photo[photo["编号"].isin(covered_photo)].copy()
    ax.scatter(covered[X_COL], covered[Y_COL], s=52, color=ORANGE, edgecolor=DARK, linewidth=0.55, alpha=0.92, zorder=7)
    label_groups = [
        ("P01/P02", ["P01", "P02"], (-58, 18)),
        ("P03/P04", ["P03", "P04"], (18, -18)),
        ("P10", ["P10"], (10, -26)),
        ("P11", ["P11"], (28, -10)),
    ]
    for label, members, offset in label_groups:
        sub = covered[covered["编号"].isin(members)]
        if sub.empty:
            continue
        xy = (float(sub[X_COL].mean()), float(sub[Y_COL].mean()))
        ax.annotate(
            label,
            xy=xy,
            xytext=offset,
            textcoords="offset points",
            fontsize=9.0,
            color=DARK,
            arrowprops=dict(arrowstyle="-", color=GRAY, lw=0.8, shrinkA=2, shrinkB=2),
            bbox=dict(boxstyle="round,pad=0.16", fc="white", ec="#C9CED6", lw=0.55, alpha=0.94),
            zorder=8,
        )
    ax.set_xlabel("X 坐标 / m")
    ax.set_ylabel("Y 坐标 / m")
    ax.set_title("联合任务方案空间分布")
    style_axis(ax, equal=True)
    handles, labels = ax.get_legend_handles_labels()
    fig.legend(handles=handles, labels=labels, frameon=False, loc="lower center", ncol=2, bbox_to_anchor=(0.5, -0.01))
    fig.subplots_adjust(left=0.10, right=0.98, top=0.92, bottom=0.18)
    save_both(fig, "joint_task_spatial_distribution")

    work = selected.sort_values("execute_time").reset_index(drop=True)
    groups = [(470, 540, "前段任务窗口"), (745, 770, "后段任务窗口")]
    fig, axes = plt.subplots(1, 2, figsize=(10.6, 5.8), gridspec_kw={"width_ratios": [1.55, 1.0]}, sharey=False)
    legend_handles = [
        mpl.patches.Patch(facecolor=BLUE, edgecolor=DARK, label="射击准备窗口"),
        mpl.patches.Patch(facecolor=ORANGE, edgecolor=DARK, label="拍照准备窗口"),
        mpl.lines.Line2D([0], [0], marker="*", color="w", markerfacecolor=DARK, markeredgecolor=DARK, label="执行时刻"),
        mpl.lines.Line2D([0], [0], marker="*", color="w", markerfacecolor=RED, markeredgecolor=RED, label="低裕度执行点"),
    ]
    for ax, (lo, hi, title) in zip(axes, groups):
        part = work[(work["execute_time"] >= lo) & (work["execute_time"] <= hi)].copy().reset_index(drop=True)
        y = np.arange(len(part))[::-1]
        for yi, (_, row) in zip(y, part.iterrows()):
            color = ORANGE if row["event_type"] == "photo" else BLUE
            ax.barh(yi, row["execute_time"] - row["start_time"], left=row["start_time"], height=0.56, color=color, alpha=0.84, edgecolor=DARK, linewidth=0.5)
            ax.plot(row["execute_time"], yi, marker="*", color=RED if row["margin"] < 0.03 else DARK, markersize=7.5, zorder=5)
        ax.set_yticks(y, part["covered_targets"].astype(str).to_list())
        ax.set_xlabel("时间 / s")
        ax.set_title(title)
        ax.set_xlim(lo, hi)
        style_axis(ax)
        ax.tick_params(axis="y", labelsize=8.4)
    axes[0].set_ylabel("目标编号")
    fig.suptitle("最终任务准备窗口与执行时刻 Gantt 图", y=0.99, fontsize=12.0)
    fig.legend(handles=legend_handles, frameon=False, ncol=2, loc="lower center", bbox_to_anchor=(0.5, -0.02))
    fig.subplots_adjust(bottom=0.20)
    save_both(fig, "joint_task_gantt_clean")


def plot_pipeline_overview() -> None:
    custom_pipeline = ROOT / "框架图.pdf"
    if custom_pipeline.exists():
        shutil.copyfile(custom_pipeline, GEN_OUT / "fig_pipeline_overview.pdf")
        return

    fig, ax = plt.subplots(figsize=(10.6, 2.8))
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")
    ax.set_facecolor("#F3F6FA")
    fig.patch.set_facecolor("#F3F6FA")

    boxes = [
        (0.035, 0.24, 0.20, 0.52, "A. 多源定位输入", "定位方式1：4 Hz\n定位方式2：5 Hz\n附件1--3轨迹数据"),
        (0.285, 0.24, 0.22, 0.52, "B. 时空配准", "估计 Delta\n固定平移型相对偏差 b\nBootstrap + 工程阈值"),
        (0.555, 0.24, 0.18, 0.52, "C. 10 Hz融合轨迹", "输出 pf(t)\n计算 v(t) 与 a(t)\n状态估计与复核"),
        (0.785, 0.24, 0.19, 0.52, "D. 固定轨迹任务优化", "可行窗口与约束筛选\nMILP + 多场景鲁棒筛选\nR5 输出：9任务/9覆盖"),
    ]
    for i, (x, y, w, h, title, body) in enumerate(boxes):
        edge = ORANGE if i == 3 else BLUE
        lw = 1.7 if i == 3 else 1.25
        rect = mpl.patches.FancyBboxPatch(
            (x, y),
            w,
            h,
            boxstyle="round,pad=0.014,rounding_size=0.018",
            linewidth=lw,
            edgecolor=edge,
            facecolor="white",
        )
        ax.add_patch(rect)
        ax.text(x + 0.018, y + h - 0.105, title, color=DARK, fontsize=10.6, weight="bold")
        ax.text(x + 0.018, y + h - 0.205, body, color="#374151", fontsize=9.2, va="top", linespacing=1.45)
    for left, right in zip(boxes[:-1], boxes[1:]):
        x0 = left[0] + left[2] + 0.012
        x1 = right[0] - 0.012
        y = 0.50
        ax.annotate(
            "",
            xy=(x1, y),
            xytext=(x0, y),
            arrowprops=dict(arrowstyle="-|>", lw=1.35, color=BLUE, shrinkA=0, shrinkB=0),
        )
    ax.annotate("误差识别", xy=(0.395, 0.79), xytext=(0.395, 0.90), ha="center",
                arrowprops=dict(arrowstyle="-|>", lw=1.0, color=GRAY), color=GRAY, fontsize=9.2)
    ax.annotate("轨迹输出", xy=(0.645, 0.79), xytext=(0.645, 0.90), ha="center",
                arrowprops=dict(arrowstyle="-|>", lw=1.0, color=GRAY), color=GRAY, fontsize=9.2)
    ax.annotate("调度决策", xy=(0.88, 0.79), xytext=(0.88, 0.90), ha="center",
                arrowprops=dict(arrowstyle="-|>", lw=1.0, color=GRAY), color=GRAY, fontsize=9.2)
    ax.text(0.5, 0.91, "多源机器人定位融合与固定轨迹任务调度总体流程", ha="center", va="center", fontsize=12.2, weight="bold", color=DARK)
    save(GEN_OUT / "fig_pipeline_overview.pdf")


def style_axis(ax: plt.Axes, equal: bool = False) -> None:
    ax.grid(alpha=0.18, linewidth=0.6)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    if equal:
        ax.axis("equal")


def read_raw(idx: int) -> tuple[pd.DataFrame, pd.DataFrame]:
    xls = B_DIR / f"附件{idx}.xlsx"
    return (
        pd.read_excel(xls, sheet_name="方式1(4Hz)"),
        pd.read_excel(xls, sheet_name="方式2(5Hz)"),
    )


def selected_r5() -> pd.DataFrame:
    return pd.read_csv(B_DIR / "outputs" / "tables" / "selected_tasks_R5_multi_uncertainty.csv")


def plot_attachment1() -> None:
    raw1, raw2 = read_raw(1)
    fused = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment1_10hz.csv")
    fig, axes = plt.subplots(1, 2, figsize=(10.0, 4.0))
    axes[0].plot(raw1[X_COL], raw1[Y_COL], color=BLUE, label="定位方式1", alpha=0.95)
    axes[0].plot(raw2[X_COL], raw2[Y_COL], color=ORANGE, label="定位方式2", alpha=0.78)
    axes[0].set_title("(a) 时间对齐前")
    axes[1].plot(fused["x1_aligned"], fused["y1_aligned"], color=BLUE, label="定位方式1")
    axes[1].plot(
        fused["x2_aligned_corrected"],
        fused["y2_aligned_corrected"],
        color=ORANGE,
        linestyle=(0, (4, 2)),
        label="对齐后的定位方式2",
    )
    axes[1].set_title("(b) 时间对齐后")
    for ax in axes:
        ax.set_xlabel("X坐标 / m")
        ax.set_ylabel("Y坐标 / m")
        style_axis(ax, equal=True)
        ax.legend(frameon=False)
    save(OUT / "fig1_attachment1_alignment.pdf")


def plot_attachment2() -> None:
    raw1, raw2 = read_raw(2)
    fused = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment2_10hz.csv")
    fig, axes = plt.subplots(1, 2, figsize=(10.0, 4.0))
    axes[0].plot(raw1[X_COL], raw1[Y_COL], color=BLUE, label="定位方式1", alpha=0.92)
    axes[0].plot(raw2[X_COL], raw2[Y_COL], color=ORANGE, label="定位方式2", alpha=0.68)
    axes[0].set_title("(a) 原始轨迹")
    axes[1].plot(fused["x1_aligned"], fused["y1_aligned"], color=BLUE, label="定位方式1")
    axes[1].plot(
        fused["x2_aligned_corrected"],
        fused["y2_aligned_corrected"],
        color=TEAL,
        linestyle=(0, (4, 2)),
        label="校正后的定位方式2",
    )
    axes[1].plot(fused[X_COL], fused[Y_COL], color=DARK, linewidth=1.0, alpha=0.78, label="融合轨迹")
    axes[1].set_title("(b) 时空配准后")
    for ax in axes:
        ax.set_xlabel("X坐标 / m")
        ax.set_ylabel("Y坐标 / m")
        style_axis(ax, equal=True)
        ax.legend(frameon=False)
    save(OUT / "fig2_attachment2_correction.pdf")


def plot_residuals2() -> None:
    res = pd.read_csv(B_DIR / "outputs" / "tables" / "attachment2_residuals.csv")
    fig, ax = plt.subplots(figsize=(5.0, 4.2))
    hb = ax.hexbin(
        res["residual_x_after"],
        res["residual_y_after"],
        gridsize=42,
        cmap="Blues",
        mincnt=1,
        linewidths=0,
    )
    ax.scatter(
        res["residual_x_after"].sample(min(800, len(res)), random_state=7),
        res["residual_y_after"].sample(min(800, len(res)), random_state=7),
        s=4,
        color=DARK,
        alpha=0.16,
        edgecolors="none",
    )
    ax.axhline(0, color=GRAY, linewidth=0.8)
    ax.axvline(0, color=GRAY, linewidth=0.8)
    ax.set_xlabel("校正后X残差 / m")
    ax.set_ylabel("校正后Y残差 / m")
    ax.set_title("附件2相对偏差校正后的残差分布")
    cbar = fig.colorbar(hb, ax=ax, fraction=0.045, pad=0.02)
    cbar.set_label("点数")
    style_axis(ax)
    save(OUT / "fig3_attachment2_residuals.pdf")


def plot_attachment3_traj() -> None:
    traj = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment3_10hz.csv")
    fig, ax = plt.subplots(figsize=(6.2, 4.7))
    points = ax.scatter(
        traj[X_COL],
        traj[Y_COL],
        c=traj[TIME_COL],
        s=7,
        cmap="viridis",
        linewidths=0,
        alpha=0.88,
    )
    ax.plot(traj[X_COL], traj[Y_COL], color=DARK, linewidth=0.5, alpha=0.32)
    ax.scatter(traj[X_COL].iloc[0], traj[Y_COL].iloc[0], s=45, color=BLUE, label="起点", zorder=5)
    ax.scatter(traj[X_COL].iloc[-1], traj[Y_COL].iloc[-1], s=45, color=ORANGE, label="终点", zorder=5)
    ax.set_xlabel("X坐标 / m")
    ax.set_ylabel("Y坐标 / m")
    ax.set_title("附件3融合后的10 Hz状态轨迹")
    cbar = fig.colorbar(points, ax=ax, fraction=0.045, pad=0.02)
    cbar.set_label("时间 / s")
    style_axis(ax, equal=True)
    ax.legend(frameon=False, loc="upper left", bbox_to_anchor=(1.02, 1.0), borderaxespad=0.0)
    fig.subplots_adjust(right=0.78)
    save(OUT / "fig4_attachment3_fused_traj.pdf")


def plot_kinematics() -> None:
    traj = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment3_10hz.csv")
    fig, axes = plt.subplots(2, 1, figsize=(8.0, 5.2), sharex=True)
    axes[0].plot(traj[TIME_COL], traj["speed"], color=BLUE)
    axes[0].fill_between(traj[TIME_COL], 0, traj["speed"], color=BLUE, alpha=0.08)
    axes[0].axhline(2.0, color=ORANGE, linestyle="--", linewidth=1.0, label="射击速度上限")
    axes[0].axhline(1.5, color=TEAL, linestyle=":", linewidth=1.2, label="拍照速度上限")
    axes[0].set_ylabel("速度 / (m/s)")
    axes[0].legend(frameon=False, ncol=2)
    axes[1].plot(traj[TIME_COL], traj["acceleration"], color=GRAY)
    axes[1].fill_between(traj[TIME_COL], 0, traj["acceleration"], color=GRAY, alpha=0.10)
    axes[1].axhline(1.5, color=ORANGE, linestyle="--", linewidth=1.0, label="加速度上限")
    axes[1].set_xlabel("时间 / s")
    axes[1].set_ylabel(r"加速度 / (m/s$^2$)", labelpad=8)
    axes[1].legend(frameon=False)
    for ax in axes:
        style_axis(ax)
    save(OUT / "fig5_attachment3_kinematics.pdf")


def read_targets() -> pd.DataFrame:
    frames = []
    for sheet, task in [("射击目标", "shooting"), ("拍照目标", "photo")]:
        df = pd.read_excel(B_DIR / "附件4.xlsx", sheet_name=sheet)
        df["task"] = task
        frames.append(df)
    return pd.concat(frames, ignore_index=True)


def plot_tasks_distribution() -> None:
    traj = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment3_10hz.csv")
    targets = read_targets()
    selected = selected_r5()
    sel_targets = set(selected["目标编号"].astype(str))
    selected_pos = traj.set_index(TIME_COL).reindex(selected["任务执行时刻(s)"].to_numpy(float), method="nearest").reset_index()
    fig, ax = plt.subplots(figsize=(6.8, 5.1))
    ax.plot(traj[X_COL], traj[Y_COL], color="#8B929A", linewidth=0.82, alpha=0.72, label="融合轨迹")
    shoot = targets[targets["task"] == "shooting"]
    photo = targets[targets["task"] == "photo"]
    ax.scatter(shoot[X_COL], shoot[Y_COL], s=26, color="#8CB9DD", alpha=0.55, label="未选射击目标")
    ax.scatter(photo[X_COL], photo[Y_COL], s=26, color="#F1B583", alpha=0.55, label="未选拍照目标")
    chosen = targets.merge(selected[["目标编号", "任务"]], left_on="编号", right_on="目标编号", how="inner")
    ax.scatter(
        chosen[X_COL],
        chosen[Y_COL],
        s=150,
        marker="*",
        color=np.where(chosen["任务"].to_numpy() == "射击", BLUE, ORANGE),
        edgecolor=DARK,
        linewidth=0.75,
        label="R5选中目标",
        zorder=5,
    )
    ax.scatter(
        selected_pos[X_COL],
        selected_pos[Y_COL],
        s=24,
        color=DARK,
        alpha=0.82,
        label="执行位置",
        zorder=4,
    )
    for _, row in chosen.iterrows():
        ax.text(row[X_COL] + 0.6, row[Y_COL] + 0.6, str(row["编号"]), fontsize=7.4, color=DARK)
    ax.set_xlabel("X坐标 / m")
    ax.set_ylabel("Y坐标 / m")
    ax.set_title("固定轨迹上的R5最终任务分布")
    style_axis(ax, equal=True)
    ax.legend(frameon=False, loc="upper left", bbox_to_anchor=(1.02, 1.0), borderaxespad=0.0)
    fig.subplots_adjust(right=0.78)
    save(OUT / "fig6_task_distribution.pdf")


def plot_timeline() -> None:
    selected = selected_r5()
    risk = pd.read_csv(B_DIR / "outputs" / "tables" / "final_task_stability_audit_v3.csv")
    risk_map = dict(zip(risk["target_id"].astype(str), risk["risk_level"].astype(str)))
    fig, axes = plt.subplots(
        1,
        2,
        figsize=(9.0, 4.8),
        sharey=True,
        gridspec_kw={"width_ratios": [3.1, 1.05], "wspace": 0.035},
    )
    labels = selected["目标编号"].astype(str).tolist()
    y_pos = np.arange(len(selected))[::-1]
    color_map = {"射击": BLUE, "拍照": ORANGE}
    axes[0].set_xlim(476.6, 511.1)
    axes[1].set_xlim(749.2, 753.1)
    for yy, (_, row) in zip(y_pos, selected.iterrows()):
        task = row["任务"]
        target = str(row["目标编号"])
        start = float(row["开始准备时刻(s)"])
        end = float(row["任务执行时刻(s)"])
        width = end - start
        is_high = risk_map.get(target, "") == "high"
        edge = RED if is_high else DARK
        lw = 1.5 if is_high else 0.7
        for ax in axes:
            xmin, xmax = ax.get_xlim()
            left = max(start, xmin)
            right = min(end, xmax)
            if right > left:
                ax.barh(
                    yy,
                    right - left,
                    left=left,
                    height=0.56,
                    color=color_map[task],
                    alpha=0.78,
                    edgecolor=edge,
                    linewidth=lw,
                )
            if xmin <= end <= xmax:
                ax.plot(end, yy, marker="*", color=RED if is_high else DARK, markersize=8.5, zorder=5)
                if is_high:
                    ax.text(end + 0.08, yy + 0.16, "边界", fontsize=7.4, color=RED)
    axes[0].set_yticks(y_pos, labels)
    axes[0].set_ylabel("最终任务")
    axes[0].set_xticks(np.arange(477, 512, 5))
    axes[1].set_xticks(np.arange(750, 754, 1))
    axes[0].set_ylim(-0.8, len(selected) - 0.2)
    axes[0].set_title("R5最终任务准备窗口与执行时序")
    axes[1].set_title("末段放大")
    fig.supxlabel("时间 / s", y=0.02)
    fig.legend(
        handles=[
            mpl.patches.Patch(facecolor=BLUE, edgecolor=DARK, alpha=0.78, label="射击准备窗口"),
            mpl.patches.Patch(facecolor=ORANGE, edgecolor=DARK, alpha=0.78, label="拍照准备窗口"),
            mpl.lines.Line2D([0], [0], marker="*", color="w", markerfacecolor=DARK, markeredgecolor=DARK, markersize=8, label="执行时刻"),
            mpl.patches.Patch(facecolor="white", edgecolor=RED, linewidth=1.5, label="高风险边界任务"),
        ],
        frameon=False,
        loc="lower center",
        ncol=4,
        bbox_to_anchor=(0.52, -0.015),
    )
    for ax in axes:
        style_axis(ax)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_visible(ax is axes[0])
    axes[1].tick_params(axis="y", left=False, labelleft=False)
    kwargs = dict(marker=[(-1, -0.45), (1, 0.45)], markersize=8, linestyle="none", color=GRAY, mec=GRAY, mew=1.0, clip_on=False)
    axes[0].plot([1, 1], [0, 1], transform=axes[0].transAxes, **kwargs)
    axes[1].plot([0, 0], [0, 1], transform=axes[1].transAxes, **kwargs)
    save(OUT / "fig7_task_timeline.pdf")


def plot_robust_model_comparison() -> None:
    df = pd.read_csv(B_DIR / "outputs" / "tables" / "robust_task_model_comparison_v3.csv")
    r1 = pd.read_csv(B_DIR / "outputs" / "tables" / "robust_task_model_comparison.csv")
    df = pd.concat([r1[r1["model"].eq("R1")], df], ignore_index=True, sort=False)
    df = df[df["model"].isin(["R1", "R3", "R4", "R5", "R6_buffered_eps_0.00"])].copy()
    df["model"] = df["model"].replace({"R6_buffered_eps_0.00": "R6"})
    order = ["R1", "R3", "R4", "R5", "R6"]
    df["model"] = pd.Categorical(df["model"], categories=order, ordered=True)
    df = df.sort_values("model")
    x = np.arange(len(df))
    fig, axes = plt.subplots(1, 2, figsize=(9.2, 3.7))
    axes[0].bar(x - 0.18, df["mean_scenario_margin_sum"], width=0.34, color=BLUE, alpha=0.88, label="平均场景裕度和")
    axes[0].bar(x + 0.18, df["worst_case_margin_sum"], width=0.34, color=TEAL, alpha=0.88, label="最坏场景裕度和")
    axes[0].set_ylabel("归一化裕度和")
    axes[0].set_xticks(x, df["model"].astype(str))
    axes[0].set_title("(a) 裕度指标")
    axes[0].legend(frameon=False)
    colors = [ORANGE if str(m) == "R5" else "#9AA6B2" for m in df["model"].astype(str)]
    axes[1].bar(x, df["scenario_feasible_rate"], width=0.56, color=colors, alpha=0.9)
    axes[1].set_ylim(0, 1.05)
    axes[1].set_ylabel("场景可行率")
    axes[1].set_xticks(x, df["model"].astype(str))
    axes[1].set_title("(b) 多场景鲁棒性")
    for ax in axes:
        style_axis(ax)
        ax.set_xlabel("模型版本")
    save(OUT / "fig8_robust_model_comparison.pdf")


def plot_smoothing_audit() -> None:
    df = pd.read_csv(B_DIR / "outputs" / "tables" / "oversmoothing_audit.csv")
    fig, axes = plt.subplots(1, 2, figsize=(9.0, 3.8))
    for poly, color in [(2, BLUE), (3, ORANGE)]:
        part = df[df["polyorder"] == poly].sort_values("window_length")
        axes[0].plot(part["window_length"], part["feasible_candidate_count"], marker="o", color=color, label=f"多项式阶数={poly}")
        axes[1].plot(part["window_length"], part["fidelity_mean"], marker="o", color=color, label=f"多项式阶数={poly}")
    axes[0].set_xlabel("Savitzky-Golay窗口长度 / 点")
    axes[0].set_ylabel("可行候选任务数")
    axes[0].set_title("(a) 候选数量敏感性")
    axes[1].set_xlabel("Savitzky-Golay窗口长度 / 点")
    axes[1].set_ylabel("平均状态估计偏移 / m")
    axes[1].set_title("(b) 轨迹状态偏移")
    for ax in axes:
        style_axis(ax)
        ax.legend(frameon=False)
    save(OUT / "fig9_smoothing_audit.pdf")


def plot_task_feasibility_heatmap() -> None:
    candidates = pd.read_csv(B_DIR / "outputs" / "tables" / "multi_uncertainty_task_pool.csv")
    if candidates.empty:
        return
    candidates = candidates.copy()
    candidates["target_task"] = candidates["目标编号"].astype(str) + candidates["任务"].astype(str)
    candidates["time_bin"] = np.floor(candidates["exec_time"].to_numpy(float) / 10.0) * 10.0
    heat = candidates.pivot_table(
        index="target_task",
        columns="time_bin",
        values="margin_mean",
        aggfunc="max",
        observed=False,
    )

    def sort_key(value: str) -> tuple[str, int]:
        text = str(value)
        prefix = text[0]
        number = int("".join(ch for ch in text if ch.isdigit()) or 0)
        return prefix, number

    heat = heat.reindex(sorted(heat.index, key=sort_key))
    values = np.ma.masked_invalid(heat.to_numpy(dtype=float))
    fig, ax = plt.subplots(figsize=(10.0, 6.2))
    cmap = mpl.colormaps["YlGnBu"].copy()
    cmap.set_bad("#ECEFF3")
    im = ax.imshow(values, aspect="auto", interpolation="nearest", cmap=cmap, vmin=0)

    x_values = heat.columns.to_numpy(dtype=float)
    step = max(1, len(x_values) // 12)
    ax.set_xticks(np.arange(len(x_values))[::step])
    ax.set_xticklabels([f"{x:.0f}" for x in x_values[::step]], rotation=45, ha="right")
    ax.set_yticks(np.arange(len(heat.index)))
    ax.set_yticklabels(heat.index)
    ax.set_xlabel("任务执行时刻 / s")
    ax.set_ylabel("目标与任务类型")
    ax.set_title("多场景候选任务的目标--时间可行性热力图")
    cbar = fig.colorbar(im, ax=ax, fraction=0.025, pad=0.02)
    cbar.set_label("最大平均稳定裕度")
    save(OUT / "fig10_task_feasibility_heatmap.pdf")


def plot_candidate_heatmap_refined() -> None:
    candidates = pd.read_csv(B_DIR / "outputs" / "tables" / "multi_uncertainty_task_pool.csv")
    selected = selected_r5()
    if candidates.empty:
        return

    windows = [(470.0, 530.0), (740.0, 760.0)]
    work = candidates[
        ((candidates["exec_time"] >= windows[0][0]) & (candidates["exec_time"] < windows[0][1]))
        | ((candidates["exec_time"] >= windows[1][0]) & (candidates["exec_time"] < windows[1][1]))
    ].copy()
    work["目标编号"] = work["目标编号"].astype(str)
    work["目标任务"] = work["目标编号"] + " " + work["任务"].astype(str)
    first_time = work.groupby(["任务", "目标编号"])["exec_time"].min()
    selected_targets = set(selected["目标编号"].astype(str))

    def row_order(item: tuple[str, str]) -> tuple[int, float, str]:
        task, target = item
        task_rank = 0 if task == "拍照" else 1
        return task_rank, float(first_time.loc[(task, target)]), target

    ordered_pairs = sorted(first_time.index.to_list(), key=row_order)
    row_labels = [f"{target} {task}" for task, target in ordered_pairs]
    row_index = {label: i for i, label in enumerate(row_labels)}
    high_risk = {"P10", "P02", "S16"}

    colors = ["#F3F4F6", "#C9DCE0", "#72AEB4", "#2F7F97", "#174A7C"]
    cmap = mpl.colors.LinearSegmentedColormap.from_list("paper_availability", colors)
    cmap.set_bad("#FFFFFF")
    vmax = 0.32
    norm = mpl.colors.Normalize(vmin=0.0, vmax=vmax)

    fig = plt.figure(figsize=(7.2, 5.0))
    gs = fig.add_gridspec(
        nrows=1,
        ncols=3,
        width_ratios=[3.0, 1.3, 0.10],
        left=0.18,
        right=0.92,
        bottom=0.13,
        top=0.88,
        wspace=0.08,
    )
    axes = [fig.add_subplot(gs[0, 0]), fig.add_subplot(gs[0, 1])]
    cax = fig.add_subplot(gs[0, 2])

    for ax, (lo, hi), panel_title in zip(axes, windows, ["(a) 470--530 s", "(b) 740--760 s"]):
        ax.set_facecolor("white")
        ax.axvspan(lo, hi, color="#F7F8FA", zorder=0)
        ax.set_xlim(lo, hi)
        ax.set_ylim(len(row_labels) - 0.5, -0.5)
        ax.set_title(panel_title, fontsize=9.5, pad=5)
        ax.grid(axis="x", color="#E5E7EB", linewidth=0.55, alpha=0.70)
        ax.grid(axis="y", color="#EEF0F3", linewidth=0.55, alpha=0.85)
        ax.set_axisbelow(True)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_color("#9CA3AF")
        ax.spines["bottom"].set_color("#9CA3AF")
        ax.tick_params(axis="both", labelsize=8.2, length=2.5, color="#6B7280")

        part = work[(work["exec_time"] >= lo) & (work["exec_time"] < hi)].copy()
        if not part.empty:
            part["time_bin"] = np.floor(part["exec_time"].to_numpy(float))
            agg = (
                part.groupby(["目标任务", "time_bin"], as_index=False)["margin_mean"]
                .max()
                .sort_values(["目标任务", "time_bin"])
            )
            for _, row in agg.iterrows():
                label = str(row["目标任务"])
                if label not in row_index:
                    continue
                y = row_index[label]
                x = float(row["time_bin"])
                value = float(row["margin_mean"])
                ax.add_patch(
                    mpl.patches.Rectangle(
                        (x, y - 0.34),
                        0.92,
                        0.68,
                        facecolor=cmap(norm(value)),
                        edgecolor="none",
                        zorder=2,
                    )
                )

        sel_part = selected[(selected["任务执行时刻(s)"] >= lo) & (selected["任务执行时刻(s)"] < hi)]
        for _, row in sel_part.iterrows():
            target = str(row["目标编号"])
            label = f"{target} {row['任务']}"
            if label not in row_index:
                continue
            is_boundary = target in high_risk
            ax.scatter(
                float(row["任务执行时刻(s)"]),
                row_index[label],
                marker="*",
                s=92 if not is_boundary else 112,
                color="#B55239" if is_boundary else "#D97904",
                edgecolor="#253238",
                linewidth=0.55,
                zorder=5,
            )
            if is_boundary:
                ax.scatter(
                    float(row["任务执行时刻(s)"]) + 0.55,
                    row_index[label],
                    marker="^",
                    s=24,
                    color="#B55239",
                    edgecolor="#253238",
                    linewidth=0.35,
                    zorder=6,
                )

    axes[0].set_yticks(np.arange(len(row_labels)))
    axes[0].set_yticklabels(row_labels)
    for tick in axes[0].get_yticklabels():
        target = tick.get_text().split()[0]
        tick.set_fontsize(8.0)
        if target in selected_targets:
            tick.set_color("#111827")
            tick.set_fontweight("bold")
        else:
            tick.set_color("#9CA3AF")
    axes[1].set_yticks(np.arange(len(row_labels)))
    axes[1].set_yticklabels([])
    axes[0].set_ylabel("目标与任务类型", fontsize=9)
    fig.supxlabel("任务执行时刻 / s", fontsize=9.2, y=0.055)
    fig.suptitle("候选任务窗口的目标--时间分布与稳定裕度", fontsize=11.0, fontweight="bold", y=0.965)

    axes[0].set_xticks(np.arange(470, 531, 10))
    axes[1].set_xticks(np.arange(740, 761, 5))
    axes[0].text(529.6, len(row_labels) - 0.25, "//", fontsize=12, color="#6B7280", ha="right", va="bottom")
    axes[1].text(740.4, len(row_labels) - 0.25, "//", fontsize=12, color="#6B7280", ha="left", va="bottom")

    sm = mpl.cm.ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])
    cbar = fig.colorbar(sm, cax=cax)
    cbar.set_label("平均稳定裕度", fontsize=8.6)
    cbar.set_ticks([0.0, 0.1, 0.2, 0.3])
    cbar.ax.tick_params(labelsize=8)
    cbar.outline.set_linewidth(0.6)

    handles = [
        mpl.patches.Patch(facecolor="#72AEB4", edgecolor="none", label="候选窗口稳定裕度"),
        mpl.lines.Line2D([0], [0], marker="*", color="w", markerfacecolor="#D97904", markeredgecolor="#253238", markersize=9, label="R5选中任务"),
        mpl.lines.Line2D([0], [0], marker="*", color="w", markerfacecolor="#B55239", markeredgecolor="#253238", markersize=9, label="边界任务"),
    ]
    axes[1].legend(handles=handles, frameon=False, loc="lower right", bbox_to_anchor=(1.02, -0.02), fontsize=8.0)

    for path in [GEN_OUT / "fig_candidate_heatmap_refined.pdf", GEN_OUT / "fig_candidate_heatmap_refined.png"]:
        kwargs = {"bbox_inches": "tight", "pad_inches": 0.03}
        if path.suffix == ".png":
            kwargs["dpi"] = 400
        fig.savefig(path, **kwargs)
    plt.close(fig)


def main() -> None:
    setup()
    copy_v4_figures()
    plot_attachment1_split_v4()
    plot_attachment12_comparison()
    plot_risk_tradeoff_clean()
    plot_attachment2_clean_v4()
    plot_time_space_speed_3d()
    plot_kinematic_smoothing_compare()
    plot_attachment3_clean_v4()
    plot_task_spatial_and_gantt_v4()
    plot_fov_risk_sensitivity()
    plot_pipeline_overview()
    plot_attachment1()
    plot_attachment2()
    plot_residuals2()
    plot_attachment3_traj()
    plot_kinematics()
    plot_tasks_distribution()
    plot_timeline()
    plot_robust_model_comparison()
    plot_smoothing_audit()
    plot_task_feasibility_heatmap()
    plot_candidate_heatmap_refined()
    try:
        from make_quality_figures import main as make_quality_figures

        make_quality_figures()
    except Exception as exc:
        print(f"quality figure generation skipped: {exc}")
    print(f"paper figures written to {OUT}")


if __name__ == "__main__":
    main()
