from __future__ import annotations

import os
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
os.environ.setdefault("MPLCONFIGDIR", str(ROOT / ".mplconfig"))

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


B_DIR = Path("/home/lux_liang/work/projects/github/数模校赛B题")
OUT = ROOT / "figures" / "paper"
GEN_OUT = ROOT / "figures" / "generated"

TIME_COL = "时间(s)"
X_COL = "X坐标(m)"
Y_COL = "Y坐标(m)"

BLUE = "#356EA9"
TEAL = "#2A9D8F"
ORANGE = "#D97732"
GRAY = "#6B7280"
DARK = "#253238"
GOLD = "#D8A31A"
RED = "#B94A48"


def setup() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    GEN_OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "v4").mkdir(parents=True, exist_ok=True)
    font_path = "/home/lux_liang/.local/texlive/2026/texmf-dist/fonts/opentype/public/fandol/FandolHei-Regular.otf"
    if Path(font_path).exists():
        mpl.font_manager.fontManager.addfont(font_path)
        zh_font = "FandolHei"
    else:
        zh_font = "DejaVu Sans"
    mpl.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": [zh_font, "DejaVu Sans"],
            "axes.unicode_minus": False,
            "font.size": 9.5,
            "axes.labelsize": 9.5,
            "axes.titlesize": 10.5,
            "legend.fontsize": 8.2,
            "xtick.labelsize": 8.5,
            "ytick.labelsize": 8.5,
            "axes.linewidth": 0.75,
            "lines.linewidth": 1.35,
            "figure.dpi": 160,
            "savefig.dpi": 320,
            "savefig.bbox": "tight",
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def save(path: Path) -> None:
    plt.tight_layout(pad=0.7)
    plt.savefig(path)
    plt.close()


def copy_v4_figures() -> None:
    """Copy v4 modeling figures generated by the coding repository into the paper tree."""

    names = [
        "attachment1_time_alignment.pdf",
        "attachment2_method_rmse_compare.pdf",
        "attachment2_trajectory_kalman_rts.pdf",
        "attachment2_residual_distribution_compare.pdf",
        "attachment3_residual_time_trend_clean.pdf",
        "attachment3_residual_vector_field_clean.pdf",
        "attachment3_bias_model_cv_compare_clean.pdf",
        "attachment3_residual_state_relation_clean.pdf",
        "attachment2_kalman_denoising.pdf",
        "attachment2_residual_before_after_kalman.pdf",
        "attachment3_residual_time_trend.pdf",
        "attachment3_residual_vector_field.pdf",
        "attachment3_bias_model_comparison.pdf",
        "attachment3_residual_vs_state.pdf",
        "shooting_hit_probability_distribution.pdf",
        "photo_multi_target_coverage.pdf",
        "joint_task_gantt.pdf",
        "joint_task_spatial_distribution.pdf",
        "joint_risk_tradeoff_curve.pdf",
    ]
    for name in names:
        src = B_DIR / "outputs" / "figures" / name
        if src.exists():
            shutil.copyfile(src, OUT / "v4" / name)


def plot_fov_risk_sensitivity() -> None:
    """Draw compact sensitivity curves for camera FOV and risk-weight tradeoff."""

    fov = pd.read_csv(B_DIR / "outputs" / "tables" / "photo_fov_sensitivity.csv")
    risk = pd.read_csv(B_DIR / "outputs" / "tables" / "joint_risk_tradeoff_curve.csv")
    fig, axes = plt.subplots(1, 2, figsize=(9.4, 3.8))

    axes[0].plot(fov["fov_degree"], fov["covered_targets"], marker="o", color=BLUE, label="覆盖拍照目标")
    axes[0].plot(fov["fov_degree"], fov["total_target_observations"], marker="s", color=TEAL, label="总观测次数")
    axes[0].plot(fov["fov_degree"], fov["multi_target_events"], marker="^", color=ORANGE, label="多目标同拍事件")
    axes[0].set_xlabel("视场角 FOV / 度")
    axes[0].set_ylabel("数量 / 个")
    axes[0].set_title("(a) FOV 灵敏度")
    axes[0].set_xticks(fov["fov_degree"])
    axes[0].legend(frameon=False)

    x = np.arange(len(risk))
    axes[1].bar(x, risk["combined_target_utility"], color=BLUE, alpha=0.82, label="综合效用")
    axes[1].set_ylabel("综合效用")
    axes[1].set_xticks(x, risk["plan_name"].astype(str), rotation=22, ha="right")
    axes[1].set_title("(b) 风险权重与裕度折中")
    ax2 = axes[1].twinx()
    ax2.plot(x, risk["risk_count"], marker="o", color=RED, label="高风险事件数")
    ax2.plot(x, risk["scenario_pass_rate"], marker="s", color=TEAL, label="场景通过率")
    ax2.set_ylabel("风险数 / 通过率")
    ax2.set_ylim(0, max(5.5, float(risk["risk_count"].max()) + 0.5))
    lines, labels = axes[1].get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    axes[1].legend(lines + lines2, labels + labels2, frameon=False, loc="upper right")

    for ax in axes:
        style_axis(ax)
    ax2.spines["top"].set_visible(False)
    ax2.grid(False)
    for path in [OUT / "v4" / "fov_risk_sensitivity.pdf", OUT / "v4" / "fov_risk_sensitivity.png"]:
        kwargs = {"bbox_inches": "tight", "pad_inches": 0.04}
        if path.suffix == ".png":
            kwargs["dpi"] = 360
        fig.savefig(path, **kwargs)
    plt.close(fig)


def plot_attachment1_split_v4() -> None:
    raw1, raw2 = read_raw(1)
    fused = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment1_10hz.csv")
    delta = pd.read_csv(B_DIR / "outputs" / "tables" / "delta_objective_attachment1.csv")

    fig, axes = plt.subplots(1, 2, figsize=(9.4, 4.0))
    axes[0].plot(raw1[X_COL], raw1[Y_COL], color=BLUE, label="定位方式1", alpha=0.95)
    axes[0].plot(raw2[X_COL], raw2[Y_COL], color=ORANGE, label="定位方式2", alpha=0.75)
    axes[0].set_title("(a) 时间对齐前")
    axes[1].plot(fused["x1_aligned"], fused["y1_aligned"], color=BLUE, label="定位方式1")
    axes[1].plot(fused["x2_aligned_corrected"], fused["y2_aligned_corrected"], color=ORANGE, linestyle=(0, (4, 2)), label="对齐后的定位方式2")
    axes[1].set_title("(b) 时间对齐后")
    for ax in axes:
        ax.set_xlabel("X 坐标 / m")
        ax.set_ylabel("Y 坐标 / m")
        style_axis(ax, equal=True)
        ax.legend(frameon=False)
    for path in [OUT / "v4" / "attachment1_trajectory_alignment_split.pdf", OUT / "v4" / "attachment1_trajectory_alignment_split.png"]:
        kwargs = {"bbox_inches": "tight", "pad_inches": 0.04}
        if path.suffix == ".png":
            kwargs["dpi"] = 360
        fig.savefig(path, **kwargs)
    plt.close(fig)

    fig, axes = plt.subplots(1, 2, figsize=(9.4, 3.9))
    best = delta.loc[delta["RMSE"].idxmin()]
    axes[0].plot(delta["Delta"], delta["RMSE"], color=BLUE)
    axes[0].scatter([best["Delta"]], [best["RMSE"]], s=42, color=RED, zorder=5, label="最优 Delta")
    axes[0].set_xlabel("时间偏差 Delta / s")
    axes[0].set_ylabel("RMSE / m")
    axes[0].set_title("(a) 时间偏差搜索曲线")
    axes[0].legend(frameon=False)
    axes[1].plot(fused[TIME_COL], fused[X_COL], color=BLUE, label="X 坐标")
    axes[1].plot(fused[TIME_COL], fused[Y_COL], color=ORANGE, label="Y 坐标")
    axes[1].set_xlabel("时间 / s")
    axes[1].set_ylabel("融合坐标 / m")
    axes[1].set_title("(b) 10 Hz 融合轨迹坐标")
    axes[1].legend(frameon=False)
    for ax in axes:
        style_axis(ax)
    for path in [OUT / "v4" / "attachment1_rmse_10hz_split.pdf", OUT / "v4" / "attachment1_rmse_10hz_split.png"]:
        kwargs = {"bbox_inches": "tight", "pad_inches": 0.04}
        if path.suffix == ".png":
            kwargs["dpi"] = 360
        fig.savefig(path, **kwargs)
    plt.close(fig)


def plot_risk_tradeoff_clean() -> None:
    risk = pd.read_csv(B_DIR / "outputs" / "tables" / "joint_risk_tradeoff_curve.csv")
    labels = ["A 收益优先", "A1 轻裕度", "A2 均衡", "B 裕度优先", "B 严格裕度"]
    fig, ax = plt.subplots(figsize=(6.8, 4.1))
    ax.plot(risk["min_margin_filter"], risk["combined_target_utility"], marker="o", color=BLUE, label="综合效用")
    ax.set_xlabel("最小裕度阈值")
    ax.set_ylabel("综合效用")
    ax.set_title("收益--风险折中曲线")
    for x, y, label in zip(risk["min_margin_filter"], risk["combined_target_utility"], labels):
        ax.annotate(label, (x, y), xytext=(4, 5), textcoords="offset points", fontsize=8.2)
    ax2 = ax.twinx()
    ax2.plot(risk["min_margin_filter"], risk["risk_count"], marker="s", color=RED, label="高风险事件数")
    ax2.plot(risk["min_margin_filter"], risk["scenario_pass_rate"], marker="^", color=TEAL, label="场景通过率")
    ax2.set_ylabel("高风险事件数 / 场景通过率")
    lines, line_labels = ax.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax.legend(lines + lines2, line_labels + labels2, frameon=False, loc="center right")
    style_axis(ax)
    ax2.spines["top"].set_visible(False)
    ax2.grid(False)
    for path in [OUT / "v4" / "joint_risk_tradeoff_curve_clean.pdf", OUT / "v4" / "joint_risk_tradeoff_curve_clean.png"]:
        kwargs = {"bbox_inches": "tight", "pad_inches": 0.04}
        if path.suffix == ".png":
            kwargs["dpi"] = 360
        fig.savefig(path, **kwargs)
    plt.close(fig)


def plot_pipeline_overview() -> None:
    custom_pipeline = ROOT / "框架图.pdf"
    if custom_pipeline.exists():
        shutil.copyfile(custom_pipeline, GEN_OUT / "fig_pipeline_overview.pdf")
        return

    fig, ax = plt.subplots(figsize=(10.6, 2.8))
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")
    ax.set_facecolor("#F3F6FA")
    fig.patch.set_facecolor("#F3F6FA")

    boxes = [
        (0.035, 0.24, 0.20, 0.52, "A. 多源定位输入", "定位方式1：4 Hz\n定位方式2：5 Hz\n附件1--3轨迹数据"),
        (0.285, 0.24, 0.22, 0.52, "B. 时空配准", "估计 Delta\n固定平移型相对偏差 b\nBootstrap + 工程阈值"),
        (0.555, 0.24, 0.18, 0.52, "C. 10 Hz融合轨迹", "输出 pf(t)\n计算 v(t) 与 a(t)\n状态估计与复核"),
        (0.785, 0.24, 0.19, 0.52, "D. 固定轨迹任务优化", "可行窗口 + 归一化裕度\nMILP + 多场景鲁棒筛选\nR5 输出：9任务/9覆盖"),
    ]
    for i, (x, y, w, h, title, body) in enumerate(boxes):
        edge = ORANGE if i == 3 else BLUE
        lw = 1.7 if i == 3 else 1.25
        rect = mpl.patches.FancyBboxPatch(
            (x, y),
            w,
            h,
            boxstyle="round,pad=0.014,rounding_size=0.018",
            linewidth=lw,
            edgecolor=edge,
            facecolor="white",
        )
        ax.add_patch(rect)
        ax.text(x + 0.018, y + h - 0.105, title, color=DARK, fontsize=10.6, weight="bold")
        ax.text(x + 0.018, y + h - 0.205, body, color="#374151", fontsize=9.2, va="top", linespacing=1.45)
    for left, right in zip(boxes[:-1], boxes[1:]):
        x0 = left[0] + left[2] + 0.012
        x1 = right[0] - 0.012
        y = 0.50
        ax.annotate(
            "",
            xy=(x1, y),
            xytext=(x0, y),
            arrowprops=dict(arrowstyle="-|>", lw=1.35, color=BLUE, shrinkA=0, shrinkB=0),
        )
    ax.text(0.5, 0.91, "多源机器人定位融合与固定轨迹任务调度总体流程", ha="center", va="center", fontsize=12.2, weight="bold", color=DARK)
    save(GEN_OUT / "fig_pipeline_overview.pdf")


def style_axis(ax: plt.Axes, equal: bool = False) -> None:
    ax.grid(alpha=0.18, linewidth=0.6)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    if equal:
        ax.axis("equal")


def read_raw(idx: int) -> tuple[pd.DataFrame, pd.DataFrame]:
    xls = B_DIR / f"附件{idx}.xlsx"
    return (
        pd.read_excel(xls, sheet_name="方式1(4Hz)"),
        pd.read_excel(xls, sheet_name="方式2(5Hz)"),
    )


def selected_r5() -> pd.DataFrame:
    return pd.read_csv(B_DIR / "outputs" / "tables" / "selected_tasks_R5_multi_uncertainty.csv")


def plot_attachment1() -> None:
    raw1, raw2 = read_raw(1)
    fused = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment1_10hz.csv")
    fig, axes = plt.subplots(1, 2, figsize=(10.0, 4.0))
    axes[0].plot(raw1[X_COL], raw1[Y_COL], color=BLUE, label="定位方式1", alpha=0.95)
    axes[0].plot(raw2[X_COL], raw2[Y_COL], color=ORANGE, label="定位方式2", alpha=0.78)
    axes[0].set_title("(a) 时间对齐前")
    axes[1].plot(fused["x1_aligned"], fused["y1_aligned"], color=BLUE, label="定位方式1")
    axes[1].plot(
        fused["x2_aligned_corrected"],
        fused["y2_aligned_corrected"],
        color=ORANGE,
        linestyle=(0, (4, 2)),
        label="对齐后的定位方式2",
    )
    axes[1].set_title("(b) 时间对齐后")
    for ax in axes:
        ax.set_xlabel("X坐标 / m")
        ax.set_ylabel("Y坐标 / m")
        style_axis(ax, equal=True)
        ax.legend(frameon=False)
    save(OUT / "fig1_attachment1_alignment.pdf")


def plot_attachment2() -> None:
    raw1, raw2 = read_raw(2)
    fused = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment2_10hz.csv")
    fig, axes = plt.subplots(1, 2, figsize=(10.0, 4.0))
    axes[0].plot(raw1[X_COL], raw1[Y_COL], color=BLUE, label="定位方式1", alpha=0.92)
    axes[0].plot(raw2[X_COL], raw2[Y_COL], color=ORANGE, label="定位方式2", alpha=0.68)
    axes[0].set_title("(a) 原始轨迹")
    axes[1].plot(fused["x1_aligned"], fused["y1_aligned"], color=BLUE, label="定位方式1")
    axes[1].plot(
        fused["x2_aligned_corrected"],
        fused["y2_aligned_corrected"],
        color=TEAL,
        linestyle=(0, (4, 2)),
        label="校正后的定位方式2",
    )
    axes[1].plot(fused[X_COL], fused[Y_COL], color=DARK, linewidth=1.0, alpha=0.78, label="融合轨迹")
    axes[1].set_title("(b) 时空配准后")
    for ax in axes:
        ax.set_xlabel("X坐标 / m")
        ax.set_ylabel("Y坐标 / m")
        style_axis(ax, equal=True)
        ax.legend(frameon=False)
    save(OUT / "fig2_attachment2_correction.pdf")


def plot_residuals2() -> None:
    res = pd.read_csv(B_DIR / "outputs" / "tables" / "attachment2_residuals.csv")
    fig, ax = plt.subplots(figsize=(5.0, 4.2))
    hb = ax.hexbin(
        res["residual_x_after"],
        res["residual_y_after"],
        gridsize=42,
        cmap="Blues",
        mincnt=1,
        linewidths=0,
    )
    ax.scatter(
        res["residual_x_after"].sample(min(800, len(res)), random_state=7),
        res["residual_y_after"].sample(min(800, len(res)), random_state=7),
        s=4,
        color=DARK,
        alpha=0.16,
        edgecolors="none",
    )
    ax.axhline(0, color=GRAY, linewidth=0.8)
    ax.axvline(0, color=GRAY, linewidth=0.8)
    ax.set_xlabel("校正后X残差 / m")
    ax.set_ylabel("校正后Y残差 / m")
    ax.set_title("附件2相对偏差校正后的残差分布")
    cbar = fig.colorbar(hb, ax=ax, fraction=0.045, pad=0.02)
    cbar.set_label("点数")
    style_axis(ax)
    save(OUT / "fig3_attachment2_residuals.pdf")


def plot_attachment3_traj() -> None:
    traj = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment3_10hz.csv")
    fig, ax = plt.subplots(figsize=(6.2, 4.7))
    points = ax.scatter(
        traj[X_COL],
        traj[Y_COL],
        c=traj[TIME_COL],
        s=7,
        cmap="viridis",
        linewidths=0,
        alpha=0.88,
    )
    ax.plot(traj[X_COL], traj[Y_COL], color=DARK, linewidth=0.5, alpha=0.32)
    ax.scatter(traj[X_COL].iloc[0], traj[Y_COL].iloc[0], s=45, color=BLUE, label="起点", zorder=5)
    ax.scatter(traj[X_COL].iloc[-1], traj[Y_COL].iloc[-1], s=45, color=ORANGE, label="终点", zorder=5)
    ax.set_xlabel("X坐标 / m")
    ax.set_ylabel("Y坐标 / m")
    ax.set_title("附件3融合后的10 Hz状态轨迹")
    cbar = fig.colorbar(points, ax=ax, fraction=0.045, pad=0.02)
    cbar.set_label("时间 / s")
    style_axis(ax, equal=True)
    ax.legend(frameon=False, loc="best")
    save(OUT / "fig4_attachment3_fused_traj.pdf")


def plot_kinematics() -> None:
    traj = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment3_10hz.csv")
    fig, axes = plt.subplots(2, 1, figsize=(8.0, 5.2), sharex=True)
    axes[0].plot(traj[TIME_COL], traj["speed"], color=BLUE)
    axes[0].fill_between(traj[TIME_COL], 0, traj["speed"], color=BLUE, alpha=0.08)
    axes[0].axhline(2.0, color=ORANGE, linestyle="--", linewidth=1.0, label="射击速度上限")
    axes[0].axhline(1.5, color=TEAL, linestyle=":", linewidth=1.2, label="拍照速度上限")
    axes[0].set_ylabel("速度 / (m/s)")
    axes[0].legend(frameon=False, ncol=2)
    axes[1].plot(traj[TIME_COL], traj["acceleration"], color=GRAY)
    axes[1].fill_between(traj[TIME_COL], 0, traj["acceleration"], color=GRAY, alpha=0.10)
    axes[1].axhline(1.5, color=ORANGE, linestyle="--", linewidth=1.0, label="加速度上限")
    axes[1].set_xlabel("时间 / s")
    axes[1].set_ylabel("加速度 / (m/s2)")
    axes[1].legend(frameon=False)
    for ax in axes:
        style_axis(ax)
    save(OUT / "fig5_attachment3_kinematics.pdf")


def read_targets() -> pd.DataFrame:
    frames = []
    for sheet, task in [("射击目标", "shooting"), ("拍照目标", "photo")]:
        df = pd.read_excel(B_DIR / "附件4.xlsx", sheet_name=sheet)
        df["task"] = task
        frames.append(df)
    return pd.concat(frames, ignore_index=True)


def plot_tasks_distribution() -> None:
    traj = pd.read_csv(B_DIR / "outputs" / "trajectories" / "fused_attachment3_10hz.csv")
    targets = read_targets()
    selected = selected_r5()
    sel_targets = set(selected["目标编号"].astype(str))
    selected_pos = traj.set_index(TIME_COL).reindex(selected["任务执行时刻(s)"].to_numpy(float), method="nearest").reset_index()
    fig, ax = plt.subplots(figsize=(6.8, 5.1))
    ax.plot(traj[X_COL], traj[Y_COL], color="#8B929A", linewidth=0.82, alpha=0.72, label="融合轨迹")
    shoot = targets[targets["task"] == "shooting"]
    photo = targets[targets["task"] == "photo"]
    ax.scatter(shoot[X_COL], shoot[Y_COL], s=26, color="#8CB9DD", alpha=0.55, label="未选射击目标")
    ax.scatter(photo[X_COL], photo[Y_COL], s=26, color="#F1B583", alpha=0.55, label="未选拍照目标")
    chosen = targets.merge(selected[["目标编号", "任务"]], left_on="编号", right_on="目标编号", how="inner")
    ax.scatter(
        chosen[X_COL],
        chosen[Y_COL],
        s=150,
        marker="*",
        color=np.where(chosen["任务"].to_numpy() == "射击", BLUE, ORANGE),
        edgecolor=DARK,
        linewidth=0.75,
        label="R5选中目标",
        zorder=5,
    )
    ax.scatter(
        selected_pos[X_COL],
        selected_pos[Y_COL],
        s=24,
        color=DARK,
        alpha=0.82,
        label="执行位置",
        zorder=4,
    )
    for _, row in chosen.iterrows():
        ax.text(row[X_COL] + 0.6, row[Y_COL] + 0.6, str(row["编号"]), fontsize=7.4, color=DARK)
    ax.set_xlabel("X坐标 / m")
    ax.set_ylabel("Y坐标 / m")
    ax.set_title("固定轨迹上的R5最终任务分布")
    style_axis(ax, equal=True)
    ax.legend(frameon=False, loc="best")
    save(OUT / "fig6_task_distribution.pdf")


def plot_timeline() -> None:
    selected = selected_r5()
    risk = pd.read_csv(B_DIR / "outputs" / "tables" / "final_task_stability_audit_v3.csv")
    risk_map = dict(zip(risk["target_id"].astype(str), risk["risk_level"].astype(str)))
    fig, axes = plt.subplots(
        1,
        2,
        figsize=(9.0, 4.8),
        sharey=True,
        gridspec_kw={"width_ratios": [3.1, 1.05], "wspace": 0.035},
    )
    labels = selected["目标编号"].astype(str).tolist()
    y_pos = np.arange(len(selected))[::-1]
    color_map = {"射击": BLUE, "拍照": ORANGE}
    axes[0].set_xlim(476.6, 511.1)
    axes[1].set_xlim(749.2, 753.1)
    for yy, (_, row) in zip(y_pos, selected.iterrows()):
        task = row["任务"]
        target = str(row["目标编号"])
        start = float(row["开始准备时刻(s)"])
        end = float(row["任务执行时刻(s)"])
        width = end - start
        is_high = risk_map.get(target, "") == "high"
        edge = RED if is_high else DARK
        lw = 1.5 if is_high else 0.7
        for ax in axes:
            xmin, xmax = ax.get_xlim()
            left = max(start, xmin)
            right = min(end, xmax)
            if right > left:
                ax.barh(
                    yy,
                    right - left,
                    left=left,
                    height=0.56,
                    color=color_map[task],
                    alpha=0.78,
                    edgecolor=edge,
                    linewidth=lw,
                )
            if xmin <= end <= xmax:
                ax.plot(end, yy, marker="*", color=RED if is_high else DARK, markersize=8.5, zorder=5)
                if is_high:
                    ax.text(end + 0.08, yy + 0.16, "边界", fontsize=7.4, color=RED)
    axes[0].set_yticks(y_pos, labels)
    axes[0].set_ylabel("最终任务")
    axes[0].set_xticks(np.arange(477, 512, 5))
    axes[1].set_xticks(np.arange(750, 754, 1))
    axes[0].set_ylim(-0.8, len(selected) - 0.2)
    axes[0].set_title("R5最终任务准备窗口与执行时序")
    axes[1].set_title("末段放大")
    fig.supxlabel("时间 / s", y=0.02)
    axes[0].legend(
        handles=[
            mpl.patches.Patch(facecolor=BLUE, edgecolor=DARK, alpha=0.78, label="射击准备窗口"),
            mpl.patches.Patch(facecolor=ORANGE, edgecolor=DARK, alpha=0.78, label="拍照准备窗口"),
            mpl.lines.Line2D([0], [0], marker="*", color="w", markerfacecolor=DARK, markeredgecolor=DARK, markersize=8, label="执行时刻"),
            mpl.patches.Patch(facecolor="white", edgecolor=RED, linewidth=1.5, label="高风险边界任务"),
        ],
        frameon=False,
        loc="lower left",
    )
    for ax in axes:
        style_axis(ax)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_visible(ax is axes[0])
    axes[1].tick_params(axis="y", left=False, labelleft=False)
    kwargs = dict(marker=[(-1, -0.45), (1, 0.45)], markersize=8, linestyle="none", color=GRAY, mec=GRAY, mew=1.0, clip_on=False)
    axes[0].plot([1, 1], [0, 1], transform=axes[0].transAxes, **kwargs)
    axes[1].plot([0, 0], [0, 1], transform=axes[1].transAxes, **kwargs)
    save(OUT / "fig7_task_timeline.pdf")


def plot_robust_model_comparison() -> None:
    df = pd.read_csv(B_DIR / "outputs" / "tables" / "robust_task_model_comparison_v3.csv")
    r1 = pd.read_csv(B_DIR / "outputs" / "tables" / "robust_task_model_comparison.csv")
    df = pd.concat([r1[r1["model"].eq("R1")], df], ignore_index=True, sort=False)
    df = df[df["model"].isin(["R1", "R3", "R4", "R5", "R6_buffered_eps_0.00"])].copy()
    df["model"] = df["model"].replace({"R6_buffered_eps_0.00": "R6"})
    order = ["R1", "R3", "R4", "R5", "R6"]
    df["model"] = pd.Categorical(df["model"], categories=order, ordered=True)
    df = df.sort_values("model")
    x = np.arange(len(df))
    fig, axes = plt.subplots(1, 2, figsize=(9.2, 3.7))
    axes[0].bar(x - 0.18, df["mean_scenario_margin_sum"], width=0.34, color=BLUE, alpha=0.88, label="平均场景裕度和")
    axes[0].bar(x + 0.18, df["worst_case_margin_sum"], width=0.34, color=TEAL, alpha=0.88, label="最坏场景裕度和")
    axes[0].set_ylabel("归一化裕度和")
    axes[0].set_xticks(x, df["model"].astype(str))
    axes[0].set_title("(a) 裕度指标")
    axes[0].legend(frameon=False)
    colors = [ORANGE if str(m) == "R5" else "#9AA6B2" for m in df["model"].astype(str)]
    axes[1].bar(x, df["scenario_feasible_rate"], width=0.56, color=colors, alpha=0.9)
    axes[1].set_ylim(0, 1.05)
    axes[1].set_ylabel("场景可行率")
    axes[1].set_xticks(x, df["model"].astype(str))
    axes[1].set_title("(b) 多场景鲁棒性")
    for ax in axes:
        style_axis(ax)
        ax.set_xlabel("模型版本")
    save(OUT / "fig8_robust_model_comparison.pdf")


def plot_smoothing_audit() -> None:
    df = pd.read_csv(B_DIR / "outputs" / "tables" / "oversmoothing_audit.csv")
    fig, axes = plt.subplots(1, 2, figsize=(9.0, 3.8))
    for poly, color in [(2, BLUE), (3, ORANGE)]:
        part = df[df["polyorder"] == poly].sort_values("window_length")
        axes[0].plot(part["window_length"], part["feasible_candidate_count"], marker="o", color=color, label=f"多项式阶数={poly}")
        axes[1].plot(part["window_length"], part["fidelity_mean"], marker="o", color=color, label=f"多项式阶数={poly}")
    axes[0].set_xlabel("Savitzky-Golay窗口长度 / 点")
    axes[0].set_ylabel("可行候选任务数")
    axes[0].set_title("(a) 候选数量敏感性")
    axes[1].set_xlabel("Savitzky-Golay窗口长度 / 点")
    axes[1].set_ylabel("平均状态估计偏移 / m")
    axes[1].set_title("(b) 轨迹状态偏移")
    for ax in axes:
        style_axis(ax)
        ax.legend(frameon=False)
    save(OUT / "fig9_smoothing_audit.pdf")


def plot_task_feasibility_heatmap() -> None:
    candidates = pd.read_csv(B_DIR / "outputs" / "tables" / "multi_uncertainty_task_pool.csv")
    if candidates.empty:
        return
    candidates = candidates.copy()
    candidates["target_task"] = candidates["目标编号"].astype(str) + candidates["任务"].astype(str)
    candidates["time_bin"] = np.floor(candidates["exec_time"].to_numpy(float) / 10.0) * 10.0
    heat = candidates.pivot_table(
        index="target_task",
        columns="time_bin",
        values="margin_mean",
        aggfunc="max",
        observed=False,
    )

    def sort_key(value: str) -> tuple[str, int]:
        text = str(value)
        prefix = text[0]
        number = int("".join(ch for ch in text if ch.isdigit()) or 0)
        return prefix, number

    heat = heat.reindex(sorted(heat.index, key=sort_key))
    values = np.ma.masked_invalid(heat.to_numpy(dtype=float))
    fig, ax = plt.subplots(figsize=(10.0, 6.2))
    cmap = mpl.colormaps["YlGnBu"].copy()
    cmap.set_bad("#ECEFF3")
    im = ax.imshow(values, aspect="auto", interpolation="nearest", cmap=cmap, vmin=0)

    x_values = heat.columns.to_numpy(dtype=float)
    step = max(1, len(x_values) // 12)
    ax.set_xticks(np.arange(len(x_values))[::step])
    ax.set_xticklabels([f"{x:.0f}" for x in x_values[::step]], rotation=45, ha="right")
    ax.set_yticks(np.arange(len(heat.index)))
    ax.set_yticklabels(heat.index)
    ax.set_xlabel("任务执行时刻 / s")
    ax.set_ylabel("目标与任务类型")
    ax.set_title("多场景候选任务的目标--时间可行性热力图")
    cbar = fig.colorbar(im, ax=ax, fraction=0.025, pad=0.02)
    cbar.set_label("最大平均稳定裕度")
    save(OUT / "fig10_task_feasibility_heatmap.pdf")


def plot_candidate_heatmap_refined() -> None:
    candidates = pd.read_csv(B_DIR / "outputs" / "tables" / "multi_uncertainty_task_pool.csv")
    selected = selected_r5()
    if candidates.empty:
        return

    windows = [(470.0, 530.0), (740.0, 760.0)]
    work = candidates[
        ((candidates["exec_time"] >= windows[0][0]) & (candidates["exec_time"] < windows[0][1]))
        | ((candidates["exec_time"] >= windows[1][0]) & (candidates["exec_time"] < windows[1][1]))
    ].copy()
    work["目标编号"] = work["目标编号"].astype(str)
    work["目标任务"] = work["目标编号"] + " " + work["任务"].astype(str)
    first_time = work.groupby(["任务", "目标编号"])["exec_time"].min()
    selected_targets = set(selected["目标编号"].astype(str))

    def row_order(item: tuple[str, str]) -> tuple[int, float, str]:
        task, target = item
        task_rank = 0 if task == "拍照" else 1
        return task_rank, float(first_time.loc[(task, target)]), target

    ordered_pairs = sorted(first_time.index.to_list(), key=row_order)
    row_labels = [f"{target} {task}" for task, target in ordered_pairs]
    row_index = {label: i for i, label in enumerate(row_labels)}
    high_risk = {"P10", "P02", "S16"}

    colors = ["#F3F4F6", "#C9DCE0", "#72AEB4", "#2F7F97", "#174A7C"]
    cmap = mpl.colors.LinearSegmentedColormap.from_list("paper_availability", colors)
    cmap.set_bad("#FFFFFF")
    vmax = 0.32
    norm = mpl.colors.Normalize(vmin=0.0, vmax=vmax)

    fig = plt.figure(figsize=(7.2, 5.0))
    gs = fig.add_gridspec(
        nrows=1,
        ncols=3,
        width_ratios=[3.0, 1.3, 0.10],
        left=0.18,
        right=0.92,
        bottom=0.13,
        top=0.88,
        wspace=0.08,
    )
    axes = [fig.add_subplot(gs[0, 0]), fig.add_subplot(gs[0, 1])]
    cax = fig.add_subplot(gs[0, 2])

    for ax, (lo, hi), panel_title in zip(axes, windows, ["(a) 470--530 s", "(b) 740--760 s"]):
        ax.set_facecolor("white")
        ax.axvspan(lo, hi, color="#F7F8FA", zorder=0)
        ax.set_xlim(lo, hi)
        ax.set_ylim(len(row_labels) - 0.5, -0.5)
        ax.set_title(panel_title, fontsize=9.5, pad=5)
        ax.grid(axis="x", color="#E5E7EB", linewidth=0.55, alpha=0.70)
        ax.grid(axis="y", color="#EEF0F3", linewidth=0.55, alpha=0.85)
        ax.set_axisbelow(True)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_color("#9CA3AF")
        ax.spines["bottom"].set_color("#9CA3AF")
        ax.tick_params(axis="both", labelsize=8.2, length=2.5, color="#6B7280")

        part = work[(work["exec_time"] >= lo) & (work["exec_time"] < hi)].copy()
        if not part.empty:
            part["time_bin"] = np.floor(part["exec_time"].to_numpy(float))
            agg = (
                part.groupby(["目标任务", "time_bin"], as_index=False)["margin_mean"]
                .max()
                .sort_values(["目标任务", "time_bin"])
            )
            for _, row in agg.iterrows():
                label = str(row["目标任务"])
                if label not in row_index:
                    continue
                y = row_index[label]
                x = float(row["time_bin"])
                value = float(row["margin_mean"])
                ax.add_patch(
                    mpl.patches.Rectangle(
                        (x, y - 0.34),
                        0.92,
                        0.68,
                        facecolor=cmap(norm(value)),
                        edgecolor="none",
                        zorder=2,
                    )
                )

        sel_part = selected[(selected["任务执行时刻(s)"] >= lo) & (selected["任务执行时刻(s)"] < hi)]
        for _, row in sel_part.iterrows():
            target = str(row["目标编号"])
            label = f"{target} {row['任务']}"
            if label not in row_index:
                continue
            is_boundary = target in high_risk
            ax.scatter(
                float(row["任务执行时刻(s)"]),
                row_index[label],
                marker="*",
                s=92 if not is_boundary else 112,
                color="#B55239" if is_boundary else "#D97904",
                edgecolor="#253238",
                linewidth=0.55,
                zorder=5,
            )
            if is_boundary:
                ax.scatter(
                    float(row["任务执行时刻(s)"]) + 0.55,
                    row_index[label],
                    marker="^",
                    s=24,
                    color="#B55239",
                    edgecolor="#253238",
                    linewidth=0.35,
                    zorder=6,
                )

    axes[0].set_yticks(np.arange(len(row_labels)))
    axes[0].set_yticklabels(row_labels)
    for tick in axes[0].get_yticklabels():
        target = tick.get_text().split()[0]
        tick.set_fontsize(8.0)
        if target in selected_targets:
            tick.set_color("#111827")
            tick.set_fontweight("bold")
        else:
            tick.set_color("#9CA3AF")
    axes[1].set_yticks(np.arange(len(row_labels)))
    axes[1].set_yticklabels([])
    axes[0].set_ylabel("目标与任务类型", fontsize=9)
    fig.supxlabel("任务执行时刻 / s", fontsize=9.2, y=0.055)
    fig.suptitle("候选任务窗口的目标--时间分布与稳定裕度", fontsize=11.0, fontweight="bold", y=0.965)

    axes[0].set_xticks(np.arange(470, 531, 10))
    axes[1].set_xticks(np.arange(740, 761, 5))
    axes[0].text(529.6, len(row_labels) - 0.25, "//", fontsize=12, color="#6B7280", ha="right", va="bottom")
    axes[1].text(740.4, len(row_labels) - 0.25, "//", fontsize=12, color="#6B7280", ha="left", va="bottom")

    sm = mpl.cm.ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])
    cbar = fig.colorbar(sm, cax=cax)
    cbar.set_label("平均稳定裕度", fontsize=8.6)
    cbar.set_ticks([0.0, 0.1, 0.2, 0.3])
    cbar.ax.tick_params(labelsize=8)
    cbar.outline.set_linewidth(0.6)

    handles = [
        mpl.patches.Patch(facecolor="#72AEB4", edgecolor="none", label="候选窗口稳定裕度"),
        mpl.lines.Line2D([0], [0], marker="*", color="w", markerfacecolor="#D97904", markeredgecolor="#253238", markersize=9, label="R5选中任务"),
        mpl.lines.Line2D([0], [0], marker="*", color="w", markerfacecolor="#B55239", markeredgecolor="#253238", markersize=9, label="边界任务"),
    ]
    axes[1].legend(handles=handles, frameon=False, loc="lower right", bbox_to_anchor=(1.02, -0.02), fontsize=8.0)

    for path in [GEN_OUT / "fig_candidate_heatmap_refined.pdf", GEN_OUT / "fig_candidate_heatmap_refined.png"]:
        kwargs = {"bbox_inches": "tight", "pad_inches": 0.03}
        if path.suffix == ".png":
            kwargs["dpi"] = 400
        fig.savefig(path, **kwargs)
    plt.close(fig)


def main() -> None:
    setup()
    copy_v4_figures()
    plot_attachment1_split_v4()
    plot_risk_tradeoff_clean()
    plot_fov_risk_sensitivity()
    plot_pipeline_overview()
    plot_attachment1()
    plot_attachment2()
    plot_residuals2()
    plot_attachment3_traj()
    plot_kinematics()
    plot_tasks_distribution()
    plot_timeline()
    plot_robust_model_comparison()
    plot_smoothing_audit()
    plot_task_feasibility_heatmap()
    plot_candidate_heatmap_refined()
    try:
        from make_quality_figures import main as make_quality_figures

        make_quality_figures()
    except Exception as exc:
        print(f"quality figure generation skipped: {exc}")
    print(f"paper figures written to {OUT}")


if __name__ == "__main__":
    main()
